id: P001675
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG24838
  title: བོད་ཀྱི་སངས་རྒྱས་ཆོས་ལུགས་ཀྱི་བྱུང་འཕེལ་ལོ་རྒྱུས།
  author: ''
  volumes:
    6f189b17490a40dd8097bb415fa1370c:
      image_group_id: I1KG24840
      title: ''
      volume_number: 1
      total_pages: 542
      base_file: v001.txt
